<a href="https://colab.research.google.com/github/DakshCodes13/EEA_WINTER_PROJECT/blob/main/ASSIGNMENT_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [79]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model
from sklearn.model_selection import train_test_split

In [80]:
df = pd.read_csv('electrical_dataset.csv')

In [81]:
df.head() #First Five Rows

Timestamp  Voltage (V)  Current (I)    Power (W)  Power_Factor  \
0  2024-12-01 00:00:00   222.483571     4.642510   965.023943      0.880626   
1  2024-12-01 00:01:00   219.308678     4.206038   894.158159      0.939144   
2  2024-12-01 00:02:00   223.238443     4.143615          NaN      0.864156   
3  2024-12-01 00:03:00   227.615149     4.188552  1006.917263      0.926711   
4  2024-12-01 00:04:00          NaN     5.165739  1081.262142      0.931754   

   Temperature (°C)  Humidity (%)  
0         21.734855     45.494834  
1               NaN     46.477508  
2         17.952615     64.195316  
3         19.613098     37.214868  
4         21.783244     55.741660

In [82]:
describe = df.describe()
print(describe) #Summarize the dataset using descriptive statistics


       Voltage (V)  Current (I)    Power (W)  Power_Factor  Temperature (°C)  \
count  9500.000000  9600.000000  9700.000000   9800.000000       9700.000000   
mean    219.992912     5.014070  1102.598216      0.919970         20.003119   
std       5.007974     0.579586   143.312091      0.040413          7.363127   
min     200.387999     4.000096   747.956441      0.850001          3.005629   
25%     216.654181     4.514213   989.925889      0.885059         13.225365   
50%     219.997444     5.020268  1100.829462      0.920172         20.011891   
75%     223.348834     5.515116  1207.908605      0.954773         26.657589   
max     239.631189     5.999850  1498.874098      0.989985         36.151952   

       Humidity (%)  
count   9600.000000  
mean      50.003748  
std       11.547591  
min       30.000337  
25%       40.117437  
50%       49.917048  
75%       60.105216  
max       69.997588  


In [83]:
df.isnull().sum()* 100 / len(df) #Identify the columns with missing values in the dataset. Calculate the percentage of missing values for each column.


Timestamp           0.0
Voltage (V)         5.0
Current (I)         4.0
Power (W)           3.0
Power_Factor        2.0
Temperature (°C)    3.0
Humidity (%)        4.0
dtype: float64

In [84]:
df['Timestamp'] = pd.to_datetime(df['Timestamp'])
df['Timestamp'].dt.time

0       00:00:00
1       00:01:00
2       00:02:00
3       00:03:00
4       00:04:00
          ...   
9995    22:35:00
9996    22:36:00
9997    22:37:00
9998    22:38:00
9999    22:39:00
Name: Timestamp, Length: 10000, dtype: object

In [85]:
df.dtypes

Timestamp           datetime64[ns]
Voltage (V)                float64
Current (I)                float64
Power (W)                  float64
Power_Factor               float64
Temperature (°C)           float64
Humidity (%)               float64
dtype: object

In [86]:
df.head()

Timestamp  Voltage (V)  Current (I)    Power (W)  Power_Factor  \
0 2024-12-01 00:00:00   222.483571     4.642510   965.023943      0.880626   
1 2024-12-01 00:01:00   219.308678     4.206038   894.158159      0.939144   
2 2024-12-01 00:02:00   223.238443     4.143615          NaN      0.864156   
3 2024-12-01 00:03:00   227.615149     4.188552  1006.917263      0.926711   
4 2024-12-01 00:04:00          NaN     5.165739  1081.262142      0.931754   

   Temperature (°C)  Humidity (%)  
0         21.734855     45.494834  
1               NaN     46.477508  
2         17.952615     64.195316  
3         19.613098     37.214868  
4         21.783244     55.741660

In [87]:
df[['Current (I)','Voltage (V)','Power (W)','Power_Factor','Temperature (°C)','Humidity (%)']] = df[['Current (I)','Voltage (V)','Power (W)','Power_Factor','Temperature (°C)','Humidity (%)']].fillna(df[['Current (I)','Voltage (V)','Power (W)','Power_Factor','Temperature (°C)','Humidity (%)']].mean())

In [88]:
#Applying suitable methods to fill missing values in the dataset. For numerical columns usage of mean is more logical because mean minimizes error when predicting a value in a data set.

In [89]:
df.head()

Timestamp  Voltage (V)  Current (I)    Power (W)  Power_Factor  \
0 2024-12-01 00:00:00   222.483571     4.642510   965.023943      0.880626   
1 2024-12-01 00:01:00   219.308678     4.206038   894.158159      0.939144   
2 2024-12-01 00:02:00   223.238443     4.143615  1102.598216      0.864156   
3 2024-12-01 00:03:00   227.615149     4.188552  1006.917263      0.926711   
4 2024-12-01 00:04:00   219.992912     5.165739  1081.262142      0.931754   

   Temperature (°C)  Humidity (%)  
0         21.734855     45.494834  
1         20.003119     46.477508  
2         17.952615     64.195316  
3         19.613098     37.214868  
4         21.783244     55.741660

In [90]:
#Detecting outliers in the 'Voltage (V)' and 'Power (W)' columns using the IQR method

In [91]:
Q1 = np.percentile(df['Voltage (V)'], 25, method='midpoint')
Q3 = np.percentile(df['Voltage (V)'], 75, method='midpoint')
IQR = Q3 - Q1
print(IQR)

upper = Q3+1.5*IQR
upper_array = np.array(df['Voltage (V)'] >= upper)
print("Upper Bound:", upper)
print(upper_array.sum())



lower = Q1-1.5*IQR
lower_array = np.array(df['Voltage (V)'] <= lower)
print("Lower Bound:", lower)
print(lower_array.sum())


6.277997022566353
Upper Bound: 232.55072228582972
65
Lower Bound: 207.4387341955643
62


In [92]:
Q1 = np.percentile(df['Power (W)'], 25, method='midpoint')
Q3 = np.percentile(df['Power (W)'], 75, method='midpoint')
IQR = Q3 - Q1
print(IQR)

upper = Q3+1.5*IQR
upper_array = np.array(df['Power (W)'] >= upper)
print("Upper Bound:", upper)
print(upper_array.sum())


# Below Lower bound
lower = Q1-1.5*IQR
lower_array = np.array(df['Power (W)'] <= lower)
print("Lower Bound:", lower)
print(lower_array.sum())


211.4499498764228
Upper Bound: 1521.9455723406063
0
Lower Bound: 676.145772834915
0


In [93]:
#Normalizing the 'Power (W)' column using Min-Max scaling

In [94]:
min = df['Power (W)'].min()
max = df['Power (W)'].max()


In [95]:
df['Power (W)'] = (df['Power (W)'] - min) / (max - min)
print(df['Power (W)'])

0       0.289070
1       0.194697
2       0.472278
3       0.344859
4       0.443865
          ...   
9995    0.583637
9996    0.627631
9997    0.325305
9998    0.683106
9999    0.841458
Name: Power (W), Length: 10000, dtype: float64


In [96]:
#Assuming the Timestamp column represents data recorded during different shifts (e.g., Morning,
#Afternoon, Evening, Night). Creating a new categorical feature, ‘Shift’ . Grouping the dataset by Shift
#and calculating the average Power (W) and Temperature for each shift.


In [97]:
df.loc[(df['Timestamp'].dt.time >= pd.to_datetime('05:00:00').time()) & (df['Timestamp'].dt.time <= pd.to_datetime('12:00:00').time()), 'Shift'] = 'Morning'
df.loc[(df['Timestamp'].dt.time >= pd.to_datetime('12:00:00').time()) & (df['Timestamp'].dt.time <= pd.to_datetime('17:00:00').time()), 'Shift'] = 'Afternoon'
df.loc[(df['Timestamp'].dt.time >= pd.to_datetime('17:00:00').time()) & (df['Timestamp'].dt.time <= pd.to_datetime('21:00:00').time()), 'Shift'] = 'Evening'
df.loc[((df['Timestamp'].dt.time >= pd.to_datetime('21:00:00').time()) & (df['Timestamp'].dt.time <= pd.to_datetime('23:59:59').time())) | ((df['Timestamp'].dt.time >= pd.to_datetime('00:00:00').time()) & (df['Timestamp'].dt.time <= pd.to_datetime('04:59:59').time())), 'Shift'] = 'Night'


In [98]:
df.head()

Timestamp  Voltage (V)  Current (I)  Power (W)  Power_Factor  \
0 2024-12-01 00:00:00   222.483571     4.642510   0.289070      0.880626   
1 2024-12-01 00:01:00   219.308678     4.206038   0.194697      0.939144   
2 2024-12-01 00:02:00   223.238443     4.143615   0.472278      0.864156   
3 2024-12-01 00:03:00   227.615149     4.188552   0.344859      0.926711   
4 2024-12-01 00:04:00   219.992912     5.165739   0.443865      0.931754   

   Temperature (°C)  Humidity (%)  Shift  
0         21.734855     45.494834  Night  
1         20.003119     46.477508  Night  
2         17.952615     64.195316  Night  
3         19.613098     37.214868  Night  
4         21.783244     55.741660  Night

In [99]:
print(df.groupby('Shift')["Power (W)"].mean())
print(df.groupby('Shift')["Temperature (°C)"].mean())

Shift
Afternoon    0.469092
Evening      0.478096
Morning      0.473506
Night        0.470237
Name: Power (W), dtype: float64
Shift
Afternoon    20.158349
Evening      20.193819
Morning      19.949209
Night        19.854380
Name: Temperature (°C), dtype: float64


In [100]:
#Creating a new feature called 'Energy_Efficiency', calculating as 'Power (W) * Power_Factor'.
#Analysing the correlation between 'Energy_Efficiency' and 'Temperature (C)’.

In [101]:
df['Energy_Efficiency'] = df['Power (W)']*df['Power_Factor']

In [102]:
df

Timestamp  Voltage (V)  Current (I)  Power (W)  Power_Factor  \
0    2024-12-01 00:00:00   222.483571     4.642510   0.289070      0.880626   
1    2024-12-01 00:01:00   219.308678     4.206038   0.194697      0.939144   
2    2024-12-01 00:02:00   223.238443     4.143615   0.472278      0.864156   
3    2024-12-01 00:03:00   227.615149     4.188552   0.344859      0.926711   
4    2024-12-01 00:04:00   219.992912     5.165739   0.443865      0.931754   
...                  ...          ...          ...        ...           ...   
9995 2024-12-07 22:35:00   226.505510     5.365876   0.583637      0.858940   
9996 2024-12-07 22:36:00   219.992912     5.699823   0.627631      0.890498   
9997 2024-12-07 22:37:00   216.473416     4.431447   0.325305      0.974504   
9998 2024-12-07 22:38:00   222.478828     5.507653   0.683106      0.883132   
9999 2024-12-07 22:39:00   223.221942     5.014070   0.841458      0.989435   

      Temperature (°C)  Humidity (%)  Shift  Energy_Efficiency  
0            21.734855     45.494834  Night           0.254562  
1            20.003119     46.477508  Night           0.182849  
2            17.952615     64.195316  Night           0.408122  
3            19.613098     37.214868  Night           0.319585  
4            21.783244     55.741660  Night           0.413573  
...                ...           ...    ...                ...  
9995         20.553140     65.807219  Night           0.501309  
9996         18.586842     35.774593  Night           0.558904  
9997         20.791749     61.015434  Night           0.317011  
9998         19.020961     50.003748  Night           0.603273  
9999         20.248707     65.940787  Night           0.832568  

[10000 rows x 9 columns]

In [103]:
corrM = df[['Energy_Efficiency','Temperature (°C)']].corr()
corrM

Energy_Efficiency  Temperature (°C)
Energy_Efficiency           1.000000         -0.007823
Temperature (°C)           -0.007823          1.000000

In [104]:
#Aggregate the data to compute the average 'Voltage (V)' and 'Current (I)' for each hour. Visualize the hourly trends.


In [105]:
df4 = df.groupby(pd.Grouper(key='Timestamp',freq='60T')).agg(Average_Voltage = ('Voltage (V)', 'mean'),Average_Current = ('Current (I)','mean'))


<ipython-input-105-e1d7e944cdf1>:1: FutureWarning: 'T' is deprecated and will be removed in a future version, please use 'min' instead.
  df4 = df.groupby(pd.Grouper(key='Timestamp',freq='60T')).agg(Average_Voltage = ('Voltage (V)', 'mean'),Average_Current = ('Current (I)','mean'))


In [106]:
df4

Average_Voltage  Average_Current
Timestamp                                            
2024-12-01 00:00:00       219.271095         5.004281
2024-12-01 01:00:00       220.088652         4.943834
2024-12-01 02:00:00       220.218292         4.936354
2024-12-01 03:00:00       220.197995         5.061464
2024-12-01 04:00:00       219.404081         5.032897
...                              ...              ...
2024-12-07 18:00:00       219.532221         4.923840
2024-12-07 19:00:00       219.861448         5.235582
2024-12-07 20:00:00       219.995573         5.107671
2024-12-07 21:00:00       220.175845         5.065138
2024-12-07 22:00:00       219.724036         4.991804

[167 rows x 2 columns]

In [107]:
#Categorizing the 'Humidity (%)' into bins

In [108]:
df.loc[(df['Humidity (%)'] >= 30) & (df['Humidity (%)'] <= 50), 'Humidity'] = 'Low'
df.loc[(df['Humidity (%)'] >= 50) & (df['Humidity (%)'] <= 60), 'Humidity'] = 'Medium'
df.loc[(df['Humidity (%)'] >= 60) & (df['Humidity (%)'] <= 70), 'Humidity'] = 'High'

In [109]:
df

Timestamp  Voltage (V)  Current (I)  Power (W)  Power_Factor  \
0    2024-12-01 00:00:00   222.483571     4.642510   0.289070      0.880626   
1    2024-12-01 00:01:00   219.308678     4.206038   0.194697      0.939144   
2    2024-12-01 00:02:00   223.238443     4.143615   0.472278      0.864156   
3    2024-12-01 00:03:00   227.615149     4.188552   0.344859      0.926711   
4    2024-12-01 00:04:00   219.992912     5.165739   0.443865      0.931754   
...                  ...          ...          ...        ...           ...   
9995 2024-12-07 22:35:00   226.505510     5.365876   0.583637      0.858940   
9996 2024-12-07 22:36:00   219.992912     5.699823   0.627631      0.890498   
9997 2024-12-07 22:37:00   216.473416     4.431447   0.325305      0.974504   
9998 2024-12-07 22:38:00   222.478828     5.507653   0.683106      0.883132   
9999 2024-12-07 22:39:00   223.221942     5.014070   0.841458      0.989435   

      Temperature (°C)  Humidity (%)  Shift  Energy_Efficiency Humidity  
0            21.734855     45.494834  Night           0.254562      Low  
1            20.003119     46.477508  Night           0.182849      Low  
2            17.952615     64.195316  Night           0.408122     High  
3            19.613098     37.214868  Night           0.319585      Low  
4            21.783244     55.741660  Night           0.413573   Medium  
...                ...           ...    ...                ...      ...  
9995         20.553140     65.807219  Night           0.501309     High  
9996         18.586842     35.774593  Night           0.558904      Low  
9997         20.791749     61.015434  Night           0.317011     High  
9998         19.020961     50.003748  Night           0.603273   Medium  
9999         20.248707     65.940787  Night           0.832568     High  

[10000 rows x 10 columns]

In [110]:
#Computing the Pearson correlation matrix for all numerical columns

In [111]:
newdf = df.select_dtypes(include='number')
corrM2 = newdf.corr()

In [112]:
corrM2

Voltage (V)  Current (I)  Power (W)  Power_Factor  \
Voltage (V)           1.000000    -0.004613   0.160901     -0.007033   
Current (I)          -0.004613     1.000000   0.846689     -0.023115   
Power (W)             0.160901     0.846689   1.000000     -0.016167   
Power_Factor         -0.007033    -0.023115  -0.016167      1.000000   
Temperature (°C)     -0.005458    -0.005771  -0.007315     -0.004042   
Humidity (%)          0.011155     0.009630   0.023447     -0.018468   
Energy_Efficiency     0.159574     0.840026   0.993060      0.093198   

                   Temperature (°C)  Humidity (%)  Energy_Efficiency  
Voltage (V)               -0.005458      0.011155           0.159574  
Current (I)               -0.005771      0.009630           0.840026  
Power (W)                 -0.007315      0.023447           0.993060  
Power_Factor              -0.004042     -0.018468           0.093198  
Temperature (°C)           1.000000     -0.014287          -0.007823  
Humidity (%)              -0.014287      1.000000           0.021558  
Energy_Efficiency         -0.007823      0.021558           1.000000

In [113]:
#Power and Energy_Efficiency are most correlated because it has the highest correlation coefficent

In [114]:
arr = df[['Voltage (V)','Current (I)','Humidity (%)','Energy_Efficiency']].to_numpy()

In [115]:
arr

array([[2.22483571e+02, 4.64251035e+00, 4.54948345e+01, 2.54562258e-01],
       [2.19308678e+02, 4.20603839e+00, 4.64775083e+01, 1.82848988e-01],
       [2.23238443e+02, 4.14361509e+00, 6.41953161e+01, 4.08121742e-01],
       ...,
       [2.16473416e+02, 4.43144698e+00, 6.10154343e+01, 3.17010845e-01],
       [2.22478828e+02, 5.50765252e+00, 5.00037480e+01, 6.03272600e-01],
       [2.23221942e+02, 5.01407008e+00, 6.59407871e+01, 8.32567625e-01]])

In [116]:
#Split the data into train and test sets (80:20 ratio) after cleaning and preprocessing and creating the linear regression model

In [117]:
x = arr
y = df['Power (W)'].to_numpy()

print("Features")
print(x)
print(x.shape)
print("Power (W)")
print(y)
print(y.shape)
#algorithm
l_reg = linear_model.LinearRegression()

x_train, x_test, y_train, y_test = train_test_split(x, y,test_size=0.2)

model = l_reg.fit(x_train, y_train)
predictions = model.predict(x_test)
print("Predictions: ",predictions)
print("R^2 value: ",l_reg.score(x, y))
print("Coeff:" , l_reg.coef_)
print("Intercept: ", l_reg.intercept_)



Features
[[2.22483571e+02 4.64251035e+00 4.54948345e+01 2.54562258e-01]
 [2.19308678e+02 4.20603839e+00 4.64775083e+01 1.82848988e-01]
 [2.23238443e+02 4.14361509e+00 6.41953161e+01 4.08121742e-01]
 ...
 [2.16473416e+02 4.43144698e+00 6.10154343e+01 3.17010845e-01]
 [2.22478828e+02 5.50765252e+00 5.00037480e+01 6.03272600e-01]
 [2.23221942e+02 5.01407008e+00 6.59407871e+01 8.32567625e-01]]
(10000, 4)
Power (W)
[0.28906965 0.1946974  0.47227785 ... 0.32530472 0.68310561 0.8414575 ]
(10000,)
Predictions:  [0.42545995 0.31687719 0.48809042 ... 0.60433177 0.39656058 0.36701446]
R^2 value:  0.986779401431432
Coeff: [3.53233707e-04 1.55400196e-02 3.90717623e-05 1.03123752e+00]
Intercept:  -0.13307592207697616


In [118]:
#here i have taken features witch have positive correlation coefficient with our target variable which is power

In [119]:
df.to_csv('electrical_dataset.csv')